update eg_wf_matrix set validactions ='Approve,Revert,Reject,Forward to Overseer,Forward to Superintendent,Forward to Secretary' where fromqty=1501 and toqty=2500 and nextstatus='Approved' and nextstate='Record Approved' and objecttype ='OccupancyCertificate' and additionalrule='OCCUPANCYCERTIFICATE';

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate)
 VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'OccupancyCertificate', 'Corporation Engineer Application Approval Pending', 'Noc Updated', 'Forwarding to secretary is pending', 'Corporation Engineer', 'OCCUPANCYCERTIFICATE', 'Corporation Engineer forwarded to secretary reviewal', 'Secretary approval pending', 'Secretary', 'NOC Updated', 'Forward', 1501, 2500, now(), '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate)
 VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'OccupancyCertificate', 'Corporation Engineer forwarded to secretary reviewal', 'Noc Updated', 'Secretary approval pending', 'Secretary', 'OCCUPANCYCERTIFICATE', 'Application reviewal completed', 'Corporation Engineer approval pending', 'Corporation Engineer', 'NOC Updated', 'Forward', 1501, 2500, now(), '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate)
 VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'OccupancyCertificate', 'Application reviewal completed', 'Noc Updated', 'Corporation Engineer approval pending', 'Corporation Engineer', 'OCCUPANCYCERTIFICATE', 'Record Approved', 'Forwarded to generate occupancy certificate', 'Corporation Engineer', 'Approved', 'Approve,Reject,Forward to Overseer,Forward to Superintendent,Forward to Secretary', 1501, 2500, now(), '2099-04-01');